config/routes.rb
Rails.application.routes.draw do

# 本家のメルカリのパスに合わせるためscopeを用いてルーティングを作成した

  # deviseGem配下で動くもの
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'user/registrations',
    # google,facebook連携ログイン用
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  scope :jp do
    # 商品一覧表示（トップページ）
    get '/'                => 'items#index'  ,as: "root"
    # 商品詳細ページ
    # get 'items/:id'      => 'items#show' (なんかこれがあると商品出品ページに飛べないので後で要確認)
    scope :mypage do
      get '/'              => 'users#mypage' ,as: "mypage"
      get 'profile'        => 'users#show'
      get 'identification' => 'users#identification'
      get 'logout'         => 'users#logout'
      get 'myitems'        => 'users#myitems'
      resources :cards, only: [:new] do
        collection do
          get  'show'      => 'cards#show'
          post 'pay'       => 'cards#pay'
          # 登録カード情報の削除
          post 'delete'    => 'cards#delete'
          # カード情報の登録のアクション
          get  'add'       => 'cards#add'
          # 購入内容の確認ページ
          get  'index'     => 'cards#index',as:"purchase"
          # カード決済のアクション
          post 'paypay'    => 'cards#paypay'
        end
      end
    end
    
    scope :transaction do
      scope :buy do
        get 'm[:id]/sell'  => 'items#transaction'
      end
    end
    # resources :item_images, only: [:create,:destroy,:update], defaults: { format: 'json' }
    #商品周りのルート
    resources :items, only: [:show, :new,:create, :edit, :update, :destroy] do
      #商品出品ページに関する、Ajaxで動くアクションのルートを作成
      collection do
        get 'purchase'     => 'items#purchase'
        get 'get_category_children', defaults: { format: 'json' }
        get 'get_category_grandchildren', defaults: { format: 'json' }
        get 'get_size', defaults: { format: 'json' }
      end
      resources :item_comments, only: [:create] do
      end
    end
  end
  
  # ユーザ新規会員登録ページ
  devise_scope :user do
    scope :jp do
      scope :signup do
        get  '/'                    => 'users/registrations#new'
        get  'registration'         => 'users/registrations#step1'
        get  'ms_confirmation'      => 'users/registrations#step2'
        get  'sms_confirmation/sms' => 'users/registrations#step3'
        get  'address'              => 'users/registrations#step4'
        get  'credit'               => 'users/registrations#step5'
        post 'registration/create'  => 'users/registrations#create'
        get  'check'                => 'users/registrations#check'
        get  'emailCheck'           => 'users/registrations#email_check'
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable,
          :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  # リレーション-----------------------------------------------------------------------------
  has_many :items
  has_one  :address
  has_one  :SnsCredential, dependent: :destroy
  has_one  :card         , dependent: :destroy

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :SnsCredential
  # ---------------------------------------------------------------------------------------
  
  
  
  
  
  
  # 独自バリデーションを定義-------------------------------------------------------------------
    # 全角カタカナ
    class KatakanaValidator < ActiveModel::EachValidator
      KATAKANA_REGEX = /\A[\p{katakana}ー－]+\z/
      def validate_each(record, attribute,value)
        if value.present?
          if value.match(KATAKANA_REGEX).blank?
            record.errors.add(attribute, '全角カタカナで入力してください')
          end
        end
      end  
    end  
    
    # 全角カナ・ひらがな・漢字
    class ZenkakuKanaHiraganaKanjiValidator < ActiveModel::EachValidator
      ZENKAKU_REGEX = /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/
      def validate_each(record, attribute,value)
        if value.present?
          if value.match(ZENKAKU_REGEX).blank?
            record.errors.add(attribute, '全角かな・ひらがな・漢字で入力してください')
          end
        end
      end  
    end
    
    # メールアドレス
    class OriginalEmailValidator < ActiveModel::EachValidator
      EMAIL_REGEX = /\A[a-zA-Z\d]+((?!\-{2,})[\w+\-])+[a-zA-Z\d]@[a-z\d]+(\.[a-z]+)*\.[a-z]+\z/i
      def validate_each(record, attribute,value)
        if value.present?
          if value.match(EMAIL_REGEX).blank?
            record.errors.add(attribute, '不正なメールアドレスです')
          end
        end
      end  
    end  
    
    # 電話番号
    class PhoneNumberValidator < ActiveModel::EachValidator
      PHONE_REGEX = /\A0[0-9]{9,11}\z/
      def validate_each(record, attribute,value)
        if value.present?
          if value.match(PHONE_REGEX).blank?
            record.errors.add(attribute, '不正な電話番号です')
          end
        end
      end
    end
  # ---------------------------------------------------------------------------------------  
  
  
  
  # 以下バリデーション------------------------------------------------------------------------
  validates :nickname       , presence: true ,length: {minimum: 2, maximum: 10 }
  validates :email          , presence: true ,uniqueness: true,original_email: true
  validates :password       , presence: true ,length: {minimum: 7, maximum: 128}
  validates :first_name     , presence: true ,zenkaku_kana_hiragana_kanji: true
  validates :last_name      , presence: true ,zenkaku_kana_hiragana_kanji: true
  validates :first_name_kana, presence: true ,katakana: true
  validates :last_name_kana , presence: true ,katakana: true
  validates :birth_year     , presence: true ,inclusion: 1900..2000
  validates :birth_month    , presence: true ,inclusion: 1..12
  validates :birth_day      , presence: true ,inclusion: 1..31
  validates :phone_number   , presence: true ,phone_number: true
  # ---------------------------------------------------------------------------------------



  #  googleとfacebookのsns認証--------------------------------------------------------------
  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = User.where(id: snscredential.user_id).first
    else
      user = User.where(email: auth.info.email).first
      if user.present?
        SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id)
      else
        user = User.new(
          nickname: auth.info.name,
          email:    auth.info.email,
          password: Devise.friendly_token[0, 20],
          phone_number: "00000000000"
          )
        SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id)
      end
    end
    return user
  end
  # ---------------------------------------------------------------------------------------
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    # リクエストデータからsnsプロバイダからの情報を取り出す
    requestData = request.env["omniauth.auth"]
    @user = User.find_oauth(requestData)
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      # sessionにプロバイダ情報を保存
      session[:provider_data]             = requestData.except("extra")
      session[:email]                     = requestData.info.email
      session[:password]                  = Devise.friendly_token[0, 20] # ランダムなパスワードを作成
      session[:provider_data]["uid"]      = requestData.uid
      session[:provider_data]["provider"] = provider.to_s
      # 会員登録ページに遷移
      redirect_to registration_path
    end
  end
  
  def failure
    redirect_to root_path && return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  skip_before_action :authenticate_user!
  before_action :validates_step1, only: :step2 # step1のバリデーション
  before_action :validates_step2, only: :step3 # step2のバリデーション


  def new
  end

  def step1
    @user = User.new()
  end
  
  def step2
    @user = User.new()
    session[:nickname]        = user_params[:nickname]
    session[:password]        = user_params[:password]  if session[:provider_data].blank?
    session[:email]           = user_params[:email]
    session[:first_name]      = user_params[:first_name]
    session[:last_name]       = user_params[:last_name]
    session[:first_name_kana] = user_params[:first_name_kana]
    session[:last_name_kana]  = user_params[:last_name_kana]
    session[:birth_year]      = user_params[:birth_year]
    session[:birth_month]     = user_params[:birth_month]
    session[:birth_day]       = user_params[:birth_day]
  end

  def step3
    @user = User.new()
    session[:phone_number]    = user_params[:phone_number]
  end
  
  def step4
    @user = User.new()
    @user.build_address(session[:address_attributes])
  end
  
  def step5
    @user = User.new()
  end
  
  def create
    if session[:provider_data].present?
      @user = User.new(
        nickname:           session[:nickname],
        email:              session[:email],
        password:           session[:password],
        first_name:         session[:first_name],
        last_name:          session[:last_name],
        first_name_kana:    session[:first_name_kana],
        last_name_kana:     session[:last_name_kana],
        birth_year:         session[:birth_year],
        birth_month:        session[:birth_month],
        birth_day:          session[:birth_day],
        phone_number:       session[:phone_number],
        address_attributes: user_params[:address_attributes],
        SnsCredential_attributes: {
          uid:              session[:provider_data]["uid"],
          provider:         session[:provider_data]["provider"],
          sns_name:         "",
          user_id:          "",
          created_at:       "",
          updated_at:       ""
        }
      )
    else
      @user = User.new(
        nickname:           session[:nickname],
        email:              session[:email],
        password:           session[:password],
        first_name:         session[:first_name],
        last_name:          session[:last_name],
        first_name_kana:    session[:first_name_kana],
        last_name_kana:     session[:last_name_kana],
        birth_year:         session[:birth_year],
        birth_month:        session[:birth_month],
        birth_day:          session[:birth_day],
        phone_number:       session[:phone_number],
        address_attributes: user_params[:address_attributes]
      )
    end
    render "step4.html.haml" unless @user.valid?
    @user.save
    sign_in @user
  end

  def check
    @user = ForbiddenWord.where(forbidden_word: user_params[:nickname]).first
    if @user.present?
      respond_to do |format|
        format.json
      end
    end
  end

  def email_check
    @user = User.where(email: user_params[:email]).first
  end

  def validates_step1
    # バリデーション用に、仮でインスタンスを作成する
    @user = User.new(
      nickname:           user_params[:nickname],
      email:              user_params[:email],
      password:           user_params[:password],
      first_name:         user_params[:first_name],
      last_name:          user_params[:last_name],
      first_name_kana:    user_params[:first_name_kana],
      last_name_kana:     user_params[:last_name_kana],
      birth_year:         user_params[:birth_year],
      birth_month:        user_params[:birth_month],
      birth_day:          user_params[:birth_day],
      phone_number:       "09012342345"
    )
    # 仮で作成したインスタンスのバリデーションチェック
    render "step1.html.haml" unless @user.valid?
  end

  def validates_step2
    # バリデーション用に、仮でインスタンスを作成する
    @user = User.new(
      nickname:           session[:nickname],
      email:              session[:email],
      password:           session[:password],
      first_name:         session[:first_name],
      last_name:          session[:last_name],
      first_name_kana:    session[:first_name_kana],
      last_name_kana:     session[:last_name_kana],
      birth_year:         session[:birth_year],
      birth_month:        session[:birth_month],
      birth_day:          session[:birth_day],
      phone_number:       user_params[:phone_number]
    )
    # 仮で作成したインスタンスのバリデーションチェック
    render "step2.html.haml" unless @user.valid?
  end 
  
  private
  def user_params
    params.require(:user).permit(
      :nickname,
      :email,
      :password,
      :first_name,
      :last_name,
      :first_name_kana,
      :last_name_kana,
      :birth_year,
      :birth_month,
      :birth_day,
      :phone_number,
      address_attributes:[:post_number,:prefecture_id, :city,:address,:building_name,:building_tel,:created_at,:updated_at,:user_id])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  skip_before_action :authenticate_user! , only: [:new, :create]
  def destroy
    super
    session[:keep_signed_out] = true
  end

  def new
    super
  end
  
  def create
    super
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def identification
    @address = Address.find(current_user.id)
    @user = User.find(current_user.id)
  end

  def show
  end

  def myitems
    @items = current_user.items
    # @item = Item.find.order("RAND(current_user)")
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # def resource_name
  #   :user
  # end

  # def resource
  #     @resource ||= User.new
  # end

  # def devise_mapping
  #     @devise_mapping ||= Devise.mappings[:user]
  # end
end

app/views/users/identification.html.haml
= render "modules/header"

%nav.iden_bread-crumbs
  .iden_bread-crumbs-box
    = link_to 'https://www.mercari.com/jp/', class: "contents" do
      メルカリ
      = fa_icon 'angle-double-right'
    = link_to 'https://www.mercari.com/jp/mypage/', class: "contents" do
      マイページ
      = fa_icon 'angle-double-right'
    %span{itemprop: "title"} 本人情報の登録

.iden_main
  .iden_main__left
    = render 'modules/mypage-sidebar'

  .iden_main__right
    %h2.iden_head 本人情報の登録
    %form.iden_form{action: "url", method: "POST", novalidate: ""} 
      %div
        %p
          お客さまの本人情報をご登録ください。
          %br>/
          登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        %p.iden_info-right
          %a.iden_info-right_link{href: "url", target: "_blank"}
            本人確認書類のアップロードについて>
            %i.icon-arrow-right
      .iden_form-group
        %label お名前
        %br/
        = current_user.first_name
        = current_user.last_name
      .iden_form-group
        %label お名前カナ
        %br/
        = current_user.first_name_kana
        = current_user.last_name_kana
      .iden_form-group
        %label{for: "birthday"} 生年月日
        %br/
        = current_user.birth_year
        年
        = current_user.birth_month
        月
        = current_user.birth_day
        日
      .iden_form-group
        %label{for: "zip_code"} 郵便番号
        %span.iden_form-arbitrary 任意
        %input.iden_form-input{name: "zip_code", placeholder: "〒", type: "text", value: @address.post_number}
      .iden_form-group
        %label{:for => "prefecture"} 都道府県
        %span.form-arbitrary 任意
        .select-wrap
          %i.fa.fa-chevron-down
          %select.select-default{name: "prefecture",placeholder: "",type: "text", value: ""}
            %option --
            %option 北海道
            %option 青森県
            %option 岩手県
            %option 宮城県
            %option 秋田県
            %option 山形県
            %option 福島県
            %option 東京都
            %option 神奈川県
            %option 埼玉県
            %option 千葉県
            %option 茨城県
            %option 栃木県
            %option 群馬県
            %option 山梨県
            %option 新潟県
            %option 長野県
            %option 富山県
            %option 石川県
            %option 福井県
            %option 愛知県
            %option 岐阜県
            %option 静岡県
            %option 三重県
            %option 大阪府
            %option 兵庫県
            %option 京都府
            %option 滋賀県
            %option 奈良県
            %option 和歌山県
            %option 鳥取県
            %option 島根県
            %option 岡山県
            %option 広島県
            %option 山口県
            %option 徳島県
            %option 香川県
            %option 愛媛県
            %option 高知県
            %option 福岡県
            %option 佐賀県
            %option 長崎県
            %option 熊本県
            %option 大分県
            %option 宮崎県
            %option 鹿児島県
            %option 沖縄県
      .iden_form-group
        %label{for: "city"} 市区町村
        %span.form-arbitrary 任意
        %input.iden_form-input{name: "city", placeholder: "", type: "text", value: @address.city}/
      .iden_form-group
        %label{for: "address1_label"} 番地
        %span.iden_form-arbitrary 任意
        %input.iden_form-input{name: "address1", placeholder: "", type: "text", value: @address.address}/
      .iden_form-group
        %label{:for => "address2_label"} 建物名
        %span.form-arbitrary 任意
        %input.iden_form-input{name: "address2", placeholder: "", type: "text", value: @address.building_name}/
      %button.iden_btn{type: "submit"} 登録する

      .iden_form-group_info-right
        %p
          %a{:href => "url", :target => "_blank"}
            本人情報の登録について>
          %i.icon-arrow-right
      %input{:name => "__csrf_value", :type => "hidden", :value => "e3822d7c75b0a6c40777ec6f3cff18bfafa93f62ff99d758079f5f68814c987eca7be2240fd94dacd22ca552b7fc0c6030b6847a03a2bca4bcbc03097374f86e5"}/

= render "modules/sell-btn"
= render 'modules/footer'

app/views/users/logout.html.haml
= render "modules/header"

%nav.logout-bread-crumbs
  .logout-bread-crumbs-box
    = link_to '/jp', class: "contents" do
      メルカリ
      = fa_icon 'angle-double-right'
    = link_to '/jp/mypage', class: "contents" do
      マイページ
      = fa_icon 'angle-double-right'
    %span{itemprop: "title"} ログアウト

.logout-main
  .logout-main__left
    = render 'modules/mypage-sidebar'

  .logout-main__right
    .logout-main__right__content
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout-btn"
= render "modules/sell-btn"
= render 'modules/footer'

app/views/users/myitems.html.haml
= render 'modules/header'
%nav.bread-crumbs
  .bread-crumbs-box
    = link_to ' /jp', class: "contents" do
      メルカリ
      = fa_icon 'chevron-right'
    %span{itemprop: "title"} プロフィール

.main-content
  = render 'modules/mypage-sidebar'

  .ryofujii-right-content
    .ryofujii-right-content__block#back-img.middle-center
      = image_tag "marunuki036.png", alt: "avatar",class: "right-content__block--avatar",size:'60x60'
      .ryofujii-right-content__block__user-name 
        = current_user.nickname
      .ryofujii-right-content__block__user-about
        %p.ryofujii-right-content__block__review 評価
        %span 156
        %p.ryofujii-right-content__block__exhibit 出品数
        %span 
          =Item.where(user_id: current_user.id).length

    .ryofujii-right-content__block
      %ul.ryofujii-right-content__block__tabs.back-gray
        %li.active.menu_item
          %h4.middle-center
            出品中

        %li.menu_item
          %h4.middle-center
            取引中

        %li.menu_item
          %h4.middle-center
            売却済み

      %ul.ryofujii-right-content__block__object
        -@items.each do |item|
          %li
            .ryofujii-right-content__block__object__link-box
              =image_tag item.item_images.first.image_url,class: "myitem-image",alt: "商品画像", size: "48x60"
              .ryofujii-right-content__block__object__link-box__body
                .ryofujii-right-content__block__object__link-box__body--text
                  = item.name
                  =link_to "編集",edit_item_path(item), class:"edit-btn"
          
        
        -# = link_to root_path, class: "decoration-none" do
          -# .ryofujii-right-content__block__object__link-box
        -#     -@items.each do |image|
        -#           = @item.name
        -#         .ryofujii-right-content__block__object__link-box__body--time
        -#           %i.fa.fa-history
                  
= render "modules/sell-btn"
= render "modules/footer"

app/views/users/show.html.haml
= render "modules/header"
-# ///////////////////////////////// パンくずlist///////////////////////////
%nav.bread-crumbs
  .bread-crumbs-box
    = link_to '/jp', class: "contents" do
      メルカリ
      = fa_icon 'angle-double-right'
    = link_to '/jp/mypage', class: "contents" do
      マイページ
      = fa_icon 'angle-double-right'
    %span{itemprop: "title"} プロフィール
-# ///////////////////////////////////////////////////////////////////////////////
.l-container.clearfix

  = render "modules/mypage-sidebar"

  .l-content
    %section.l-chapter-container
      %h2.l-chapter-head プロフィール
      %form{:action => "https://www.mercari.com/jp/mypage/profile/", :method => "POST"}
        %input{:name => "__csrf_value", :type => "hidden", :value => "3c4f11465244650df31f45c7ae9fd640b5106547cef796d0b550904a6a9caef0e0ff6bfb18a9df809256bf3b41457777a9610f294078b4f08ac73e31ab382d587"}/
        .setting-profile-icon
          %figure
            %img{:height => "60", :src => "//static.mercdn.net/images/member_photo_noimage_thumb.png", :width => "60"}/
          %input.input-default{:name => "nickname", :placeholder => "例)AYA☆セール中", :type => "text", :value => ""}/
        .setting-profile-content
          %textarea.textarea-default{:name => "introduction", :placeholder => "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"}
          %input{:name => "after_save_callback", :type => "hidden", :value => "https://www.mercari.com/jp/mypage/profile/"}/
          %button.btn-default.btn-red{:type => "submit"} 変更する

= render "modules/sell-btn"
= render "modules/footer"