config/routes.rb
Rails.application.routes.draw do

# 本家のメルカリのパスに合わせるためscopeを用いてルーティングを作成した

  # deviseGem配下で動くもの
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'user/registrations',
    # google,facebook連携ログイン用
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  scope :jp do
    # 商品一覧表示（トップページ）
    get '/'                => 'items#index'  ,as: "root"
    # 商品詳細ページ
    # get 'items/:id'      => 'items#show' (なんかこれがあると商品出品ページに飛べないので後で要確認)
    scope :mypage do
      get '/'              => 'users#mypage' ,as: "mypage"
      get 'profile'        => 'users#show'
      get 'identification' => 'users#identification'
      get 'logout'         => 'users#logout'
      get 'myitems'        => 'users#myitems'
      resources :cards, only: [:new] do
        collection do
          get  'show'      => 'cards#show'
          post 'pay'       => 'cards#pay'
          # 登録カード情報の削除
          post 'delete'    => 'cards#delete'
          # カード情報の登録のアクション
          get  'add'       => 'cards#add'
          # 購入内容の確認ページ
          get  'index'     => 'cards#index',as:"purchase"
          # カード決済のアクション
          post 'paypay'    => 'cards#paypay'
        end
      end
    end
    
    scope :transaction do
      scope :buy do
        get 'm[:id]/sell'  => 'items#transaction'
      end
    end
    # resources :item_images, only: [:create,:destroy,:update], defaults: { format: 'json' }
    #商品周りのルート
    resources :items, only: [:show, :new,:create, :edit, :update, :destroy] do
      #商品出品ページに関する、Ajaxで動くアクションのルートを作成
      collection do
        get 'purchase'     => 'items#purchase'
        get 'get_category_children', defaults: { format: 'json' }
        get 'get_category_grandchildren', defaults: { format: 'json' }
        get 'get_size', defaults: { format: 'json' }
      end
      resources :item_comments, only: [:create] do
      end
    end
  end
  
  # ユーザ新規会員登録ページ
  devise_scope :user do
    scope :jp do
      scope :signup do
        get  '/'                    => 'users/registrations#new'
        get  'registration'         => 'users/registrations#step1'
        get  'ms_confirmation'      => 'users/registrations#step2'
        get  'sms_confirmation/sms' => 'users/registrations#step3'
        get  'address'              => 'users/registrations#step4'
        get  'credit'               => 'users/registrations#step5'
        post 'registration/create'  => 'users/registrations#create'
        get  'check'                => 'users/registrations#check'
        get  'emailCheck'           => 'users/registrations#email_check'
      end
    end
  end
end

app/views/modules/_footer.html.haml
.app-banner
  .app-banner-pc
    .app-banner-icon.clearfix
    %figure
%footer.global-footer
  %nav.clearfix
    .footer-cell
      .footer-head メルカリについて
      %ul
        %li
          = link_to '会社概要（運営会社)','https://about.mercari.com/'
        %li
          = link_to '採用情報', 'https://www.mercari.com/jp/jobs/'
        %li

          = link_to 'プレスリリース', 'https://about.mercari.com/press/news/'
        %li
          = link_to '公式ブログ', 'https://jp-news.mercari.com/'
        %li
          = link_to 'メルカリロゴ利用ガイドライン', 'https://www.mercari.com/jp/logo-guidelines/'
        .footer-social-link
          =link_to "https://www.facebook.com/", class: "contents__btn--facebook" do
            = fa_icon 'facebook', class: "contents__btn--facebook"
          =link_to "https://twitter.com/", class: "contents__btn contents__btn--twitter" do
            = fa_icon 'twitter', class: "contents__btn--facebook"
          
    .footer-cell
      %h2.footer-head ヘルプ＆ガイド
      %ul
        %li
          = link_to 'メルカリガイド', 'https://www.mercari.com/jp/help_center/'
        %li
          = link_to 'らくらくメルカリ便', 'https://www.mercari.com/jp/rakuraku-mercari/'
        %li
          = link_to 'ゆうゆうメルカリ便', 'https://www.mercari.com/jp/yuyu-mercari/'
        %li
          = link_to '大型メルカリ便', 'https://www.mercari.com/jp/rakuraku-ogata/'
        %li
          = link_to '車体取引ガイド', 'https://www.mercari.com/jp/guide/car/'
        %li
          = link_to 'メルカリあんしん・あんぜん宣言！', 'https://www.mercari.com/jp/safe/description/'
        %li
          = link_to '偽ブランド品撲滅への取り組み', 'https://www.mercari.com/jp/authenticity/'
        %li
          = link_to 'メルカリボックス', 'https://www.mercari.com/jp/box/'
    .full-width
      %h2.footer-head プライバシーと利用規約
      .inner-footer-cell
        %ul
          %li
            = link_to 'プライバシーポリシー', 'https://www.mercari.com/jp/privacy/'
          %li
            = link_to 'メルカリ利用規約', 'https://www.mercari.com/jp/tos/'
          %li
            = link_to 'あんしんスマホサポート制度に関する利用特約', 'https://www.mercari.com/jp/tos_smartphone_support/'
          %li
            = link_to 'コンプライアンスポリシー', 'https://www.mercari.com/jp/compliance/'
      .inner-footer-cell
        %ul
          %li
            = link_to '個人データの安全管理に係る基本方針', 'https://www.mercari.com/jp/data_security/'
          %li
            = link_to '特定商取引に関する表記', 'https://www.mercari.com/jp/tokutei/'
          %li
            = link_to '資金決済法に基づく表示','https://www.mercari.com/jp/shikin_kessai/'
          %li
            = link_to '法令順守と犯罪抑止のために','https://about.mercari.com/csr/safety/'
    .footer-nav-lang
      %h2.footer-head 国
      %ul
        %li
          = link_to '日本','https://www.mercari.com/jp/'
        %li
          = link_to 'United States','https://www.mercari.com/'
  .footer-bottom
    .footer-logo
      = image_tag ('https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?4248847005')
    .footer-copyright
      © 2019 Mercari

app/views/modules/_header.html.haml
%header.main-header
  .main-header-inner
    .main-header-inner-top
      .main-header-inner-top__left
        = link_to root_path, class:"content" do
          = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3270184656", size: "134x36", alt: "メルカリロゴ", class: "header__box__top__link__image"
      .main-header-inner-top-right
        .main-header-inner-top-right-form
          %form
            %input.input-default{name: "keyword", placeholder: "何かお探しですか？", type: "search", value: ""}/
        .main-header-inner-top-right-musimegane
          %i.fa.fa-search
    .main-header-nav-box
      %nav.l-left
        %ul.main-header-nav
          %li
            %h2
              .main-header-nav-root.list-parent
                %i.fa.fa-list.ul
                %span カテゴリーから探す
          %li
            %h2
              .main-header-nav-root.list-parent
                %i.fa.fa-tags
                %span ブランドから探す
      %nav.l-right
        %ul.main-header-user-nav
          - if user_signed_in?
            %li
              .main-header-menu-link
                %i.fa.fa-bell
                %span お知らせ
            %li
              .main-header-menu-link
                %i.fa.fa-check
                %span やることリスト
            %li
              .main-header-menu-link
                = link_to "マイページ",mypage_path, class: "decoration-none" 
          - else
            %li
              = link_to "ログイン", new_user_session_path, class: "login-link"
            %li
              = link_to "新規会員登録", "/jp/signup", class: "registration-link"

app/views/modules/_mypage-sidebar.html.haml
.left-content
  .left-content__bar
    %ul
      %li.notborder
        =link_to "マイページ", mypage_path
        %i.fa.fa-chevron-right
      %li
        %a お知らせ
        %i.fa.fa-chevron-right
      %li
        %a やることリスト
        %i.fa.fa-chevron-right
      %li
        %a いいね！一覧
        %i.fa.fa-chevron-right
      %li
        =link_to "出品する",new_item_path
        %i.fa.fa-chevron-right
      %li
        =link_to "出品した商品-出品中",myitems_path
        %i.fa.fa-chevron-right
      %li
        %a 出品した商品-取引中
        %i.fa.fa-chevron-right
      %li
        %a 出品した商品-売却済み
        %i.fa.fa-chevron-right
      %li
        %a  購入した商品-取引中
        %i.fa.fa-chevron-right
      %li
        %a 購入した商品-過去の取引
        %i.fa.fa-chevron-right
      %li
        %a ニュース一覧
        %i.fa.fa-chevron-right
      %li
        %a 評価一覧
        %i.fa.fa-chevron-right
      %li
        %a ガイド
        %i.fa.fa-chevron-right
      %li
        %a お問い合わせ
        %i.fa.fa-chevron-right
  .left-content__bar
    %h4 メルペイ
    %ul.marginT-8px
      %li
        %a 売上・振込申請
        %i.fa.fa-chevron-right
      %li
        %a ポイント
        %i.fa.fa-chevron-right
  .left-content__bar
    %h4 設定
    %ul.marginT-8px
      %li
        =link_to "プロフィール",profile_path
        %i.fa.fa-chevron-right
      %li
        %a 住所変更
        %i.fa.fa-chevron-right
      %li
        =link_to "支払い方法" ,cards_path
        %i.fa.fa-chevron-right
      %li
        %a メール/パスワード
        %i.fa.fa-chevron-right
      %li
        =link_to "本人情報" ,identification_path 
        %i.fa.fa-chevron-right
      %li
        %a 電話番号の確認
        %i.fa.fa-chevron-right
      %li
        =link_to "ログアウト",logout_path
        %i.fa.fa-chevron-right

app/views/modules/_sell-btn.html.haml
%a{href: new_item_path,class:"footer-sell-btn decoration-none"}
  %div 出品
  %i.icon-camera
  = fa_icon 'camera', class: "contents__btn--icon"