config/routes.rb
Rails.application.routes.draw do

# 本家のメルカリのパスに合わせるためscopeを用いてルーティングを作成した

  # deviseGem配下で動くもの
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'user/registrations',
    # google,facebook連携ログイン用
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  scope :jp do
    # 商品一覧表示（トップページ）
    get '/'                => 'items#index'  ,as: "root"
    # 商品詳細ページ
    # get 'items/:id'      => 'items#show' (なんかこれがあると商品出品ページに飛べないので後で要確認)
    scope :mypage do
      get '/'              => 'users#mypage' ,as: "mypage"
      get 'profile'        => 'users#show'
      get 'identification' => 'users#identification'
      get 'logout'         => 'users#logout'
      get 'myitems'        => 'users#myitems'
      resources :cards, only: [:new] do
        collection do
          get  'show'      => 'cards#show'
          post 'pay'       => 'cards#pay'
          # 登録カード情報の削除
          post 'delete'    => 'cards#delete'
          # カード情報の登録のアクション
          get  'add'       => 'cards#add'
          # 購入内容の確認ページ
          get  'index'     => 'cards#index',as:"purchase"
          # カード決済のアクション
          post 'paypay'    => 'cards#paypay'
        end
      end
    end
    
    scope :transaction do
      scope :buy do
        get 'm[:id]/sell'  => 'items#transaction'
      end
    end
    # resources :item_images, only: [:create,:destroy,:update], defaults: { format: 'json' }
    #商品周りのルート
    resources :items, only: [:show, :new,:create, :edit, :update, :destroy] do
      #商品出品ページに関する、Ajaxで動くアクションのルートを作成
      collection do
        get 'purchase'     => 'items#purchase'
        get 'get_category_children', defaults: { format: 'json' }
        get 'get_category_grandchildren', defaults: { format: 'json' }
        get 'get_size', defaults: { format: 'json' }
      end
      resources :item_comments, only: [:create] do
      end
    end
  end
  
  # ユーザ新規会員登録ページ
  devise_scope :user do
    scope :jp do
      scope :signup do
        get  '/'                    => 'users/registrations#new'
        get  'registration'         => 'users/registrations#step1'
        get  'ms_confirmation'      => 'users/registrations#step2'
        get  'sms_confirmation/sms' => 'users/registrations#step3'
        get  'address'              => 'users/registrations#step4'
        get  'credit'               => 'users/registrations#step5'
        post 'registration/create'  => 'users/registrations#create'
        get  'check'                => 'users/registrations#check'
        get  'emailCheck'           => 'users/registrations#email_check'
      end
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :item_images, dependent: :destroy
  belongs_to :user
  belongs_to :item_state
  belongs_to :size, optional: true
  belongs_to :delivery_fee
  belongs_to :delivery_method
  belongs_to :delivery_day
  belongs_to :category,optional: true
  belongs_to_active_hash :prefecture
  accepts_nested_attributes_for :item_images
  has_many :item_comments

  validates :name, presence: true, length: { maximum: 40 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
  validates :brand, presence: true
  validates :category_id, presence: true
  validates :item_state_id, presence: true
  validates :delivery_fee_id, presence: true
  validates :delivery_method_id, presence: true
  validates :delivery_day_id, presence: true
  validates :user_id, presence: true
  validates :prefecture_id, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  # before_action :user_login,only:[:new, :show]

  def index
    @item = Item.order("created_at DESC").limit(4).where.not(item_state_id: 2)
    @items_for_woman = Category.get_items_for(1).first(4)
    @items_for_man = Category.get_items_for(200).first(4)
    @items_for_sports = Category.get_items_for(399).first(4)
    @items_for_interior = Category.get_items_for(598).first(4)
  end
  
  def show
    @item = Item.find(params[:id])
    @images = @item.item_images
    @item_user = Item.where("user_id = ?", @item.user_id).order("created_at asc").limit(3)
    @products = Item.order("RAND()").limit(3)
    @next_item = Item.where("id > ?", @item.id).order("id ASC").first
    @prev_item = Item.where("id < ?", @item.id).order("id DESC").first
    @comments = @item.item_comments.includes(:user).order("id DESC")
  end

  def new
    @item = Item.new
    10.times{@item.item_images.build}
    #セレクトボックスの初期値設定
    @category_parent_array = ["---"]
    #データベースから、親カテゴリーのみ抽出し、配列化
    @category_parent_array = Category.where(ancestry: nil)
  end
  
  # 以下全て、formatはjsonのみ
  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find("#{params[:parent_id]}").children
  end
  
  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end
  
  # 孫カテゴリーが選択された後に動くアクション
  def get_size
    selected_grandchild = Category.find("#{params[:grandchild_id]}") #JSから送られてきた、孫カテゴリーのidを元に、選択された孫カテゴリーのレコードを取得
    if related_size_parent = selected_grandchild.sizes[0] #孫カテゴリーと紐付くサイズ（親）があれば取得
      @sizes = related_size_parent.children #紐づいたサイズ（親）の子供の配列を取得
    else
      selected_child = Category.find("#{params[:grandchild_id]}").parent #選択された孫カテゴリーの親（子カテゴリー）のレコードを取得
      if related_size_parent = selected_child.sizes[0] #子カテゴリーと紐付くサイズ（親）があれば取得
        @sizes = related_size_parent.children #紐づいたサイズ（親）の子供の配列を取得
      end
    end
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to :root
    else
      redirect_to :new_item
    end
  end
  # ----------------------------------------------------
  def edit
    @item = Item.find(params[:id])
    @images = @item.item_images
    @category_parent_array = Category.where(ancestry: nil)
    @category_child_array = @item.category.parent.siblings
    @category_grandchild_array = @item.category.siblings


  end

  def update
    @item = Item.find(params[:id])
    @images = @item.item_images
    if @item.update(item_params)
      redirect_to root_path, notice: '商品を編集しました'
    else
      render :edit
    end
  end

# ------------------------------------------------------
  def destroy
    item = Item.find(params[:id])
    if item.user_id == current_user.id
      item.destroy
    end
    redirect_to root_path
  end

  def transaction
  end


  private
  def item_params
    params.require(:item).permit(
      :name,
      :description,
      :brand,
      :item_state_id,
      :delivery_fee_id,
      :delivery_method_id,
      :delivery_day_id,
      :price,
      :category_id,
      :prefecture_id,
      :size_id,
      item_images_attributes: [:image, :id]
    ).merge(user_id: current_user.id)
  end
end

app/controllers/jp/items_controller.rb
class Jp::ItemsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def purchase
  end

  def destroy
    item = Item.find(params[:id])
    if item.user_id == current_user.id
    item.destroy
    end
    redirect_to root_path
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_image.html.haml
%li.listGroupItem
  = image_tag image,width:"120px",height:"80px",class:"item-image",data:{"image_id": "#{image_id}"}
  - if image.filename
    - filename = image.filename
  - else
    - filename = "#{image.model[:images][image_counter]}"
  %div#deleteBtn--pre{data:{"image_index": "#{image_counter+length}", "image_original_index": "#{image_counter+original_index}", "image_filename": "#{filename}"}}
    %span.edit-image
      編集
    %span.delete-image
      削除

app/views/items/edit.html.haml
.sell__header
  =link_to root_path do
    =image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?863303983", alt: "mercari", class: "sign-up__header--image"
.sell-main
  .sell-inner
    %h2.sell-inner__head 商品の情報を入力
    .sell-inner__form
    = form_for @item, method: :patch do |f|
      .sell-inner__form__upload-box
        %label 出品画像
        %span 必須
        %p.sell-inner__form__upload-box-text 既存画像の変更
        .sell-inner__form__upload-box__dropbox
          .sell-inner__form__upload-box__dropbox__container
            %pre
              :preserve
                ドラッグアンドドロップ
                またはクリックしてファイルをアップロード


            .preview
            - @images.each do |image|
              = image_tag image.image.url
            =f.fields_for :item_images do |i|
              = i.file_field :image,type:"file" ,multipule: true, id: 'image_select'


      .sell-inner__form__item
        .sell-inner__form__item__name
          = f.label :商品名, class: "label"
          %span 必須
          %div
            = f.text_field :name, required: true, placeholder: "商品名（40字まで）", class: "inputField"

        .sell-inner__form__item__description
          = f.label :商品の説明
          %span 必須
          = f.text_area :description, required: true, placeholder: "商品説明（1,000字まで）例）2018年に購入した、革ジャンです。黒みがかった見た目です。傷等はございません。", class: "inputField inputField__area", rows: "7"

      .sell-inner__form__content
        .sell-inner__form__content__left
          %h3 商品の詳細
        .sell-inner__form__content__right
          #sell-inner__form__content__right__genre_hogehoge
            = f.label 'カテゴリー'
            %span 必須
            .sell-inner__form__content__right__genre__select
              %i.fa.fa-chevron-down
              = f.collection_select :category_id, @category_parent_array, :id, :name, id: 'parent_category', selected: @item.category.root.name
            .sell-inner__form__content__right__genre__select
              %i.fa.fa-chevron-down
              = f.collection_select :category_id, @category_child_array, :id, :name, id: 'grandchild_category', selected: @item.category.parent.name
            .sell-inner__form__content__right__genre__select
              %i.fa.fa-chevron-down
              = f.collection_select :category_id, @category_grandchild_array, :id, :name, id: 'grandchild_category', selected: @item.category.name
            -if @item.size.present?
              .sell-inner__form__content__right__genre
                %label サイズ
                %span 必須
                .sell-inner__form__content__right__genre__select
                  %i.fa.fa-chevron-down
                  = f.collection_select :size_id, @item.size.siblings, :id, :name, id: 'size', selected: @item.size.name


          .sell-inner__form__content__right__genre
            %label ブランド
            %span 必須
            .sell-inner__form__content__right__genre__select
              = f.text_field :brand, required: true, placeholder: "例)フェラガモ", class: "inputbrand"
          .sell-inner__form__content__right__genre
            %label 商品の状態
            %span 必須
            .sell-inner__form__content__right__genre__select
              %i.fa.fa-chevron-down
              = f.collection_select :item_state_id,ItemState.all, :id, :item_state,{include_blank: "---"},{required:true}

      .sell-inner__form__content
        .sell-inner__form__content__left
          %h3 配送について
          = link_to do
            = fa_icon 'question-circle', class: 'question-circle'
        .sell-inner__form__content__right
          #sell-inner__form__content__right__genre
            %label 配送料の負担
            %span 必須
            .sell-inner__form__content__right__genre__select
              %i.fa.fa-chevron-down
              = f.collection_select :delivery_fee_id,DeliveryFee.all, :id, :delivery_fee,{include_blank: "---"},{required:true}

          .sell-inner__form__content__right__genre
            %label 配送の方法
            %span 必須
            .sell-inner__form__content__right__genre__select
              %i.fa.fa-chevron-down
              = f.collection_select :delivery_method_id,DeliveryMethod.all, :id, :delivery_method,{include_blank: "---"},{required:true}

          .sell-inner__form__content__right__genre
            %label 配送元の地域
            %span 必須
            .sell-inner__form__content__right__genre__select
              %i.fa.fa-chevron-down
              = f.collection_select :prefecture_id, Prefecture.all, :id, :name,{include_blank: "---"},{required:true}

          .sell-inner__form__content__right__genre
            %label 配送までの日数
            %span 必須
            .sell-inner__form__content__right__genre__select
              %i.fa.fa-chevron-down
              = f.collection_select :delivery_day_id,DeliveryDay.all, :id, :delivery_day,{include_blank: "---"},{required:true}

      .sell-inner__form__content
        .sell-inner__form__content__left
          %h3 販売価格(300~9,999,999)
          = link_to do
            = fa_icon 'question-circle', class: 'question-circle'
        .sell-inner__form__content__right
          .sell-inner__form__content__right__price
            .sell-inner__form__content__right__price__genre
              %label 価格
              %span 必須
            .sell-inner__form__content__right__price__frame
              .sell-inner__form__content__right__price__frame__mark ¥
              .sell-inner__form__content__right__price__frame__box
                = f.text_field :price, required: true, placeholder: "例）300", class: "inputprice"            
          .sell-inner__form__content__right__fee
            .sell-inner__form__content__right__fee__text
              %p 販売手数料(10%)
            .sell-inner__form__content__right__fee__integer
              %p
              
          .sell-inner__form__content__right__profit
            .sell-inner__form__content__right__profit__text
              %h3 販売利益
            .sell-inner__form__content__right__profit__integer
              %h3

      .sell-inner__form__foot
        .sell-inner__form__foot__text
          %p
            %a{:href => "/jp/help_center/getting_started/prohibited_items/", :target => "_blank"} 禁止されている出品
            、
            %a{:href => "/jp/help_center/getting_started/prohibited_conduct/", :target => "_blank"} 行為
            を必ずご確認ください。
          %p
            またブランド品でシリアルナンバー等がある場合はご記載ください。
            %a{:href => "/jp/help_center/getting_started/counterfeit_goods/", :target => "_blank"} 偽ブランドの販売
            は犯罪であり処罰される可能性があります。
          %p
            また、出品をもちまして
            %a{:href => "/jp/seller_terms/"} 加盟店規約
            に同意したことになります。

        .sell-inner__form__foot__btn
          %button.sell-inner__form__foot__btn__sell{type: "submit"}
            = f.submit "更新する", class:"submit-btn"
          .sell-inner__form__foot__btn__back
            = link_to "もどる", :back, class: "sell-inner__form__foot__btn__back__btn"

.sell__footer
  %nav
    %ul
      %li
        プライバシーポリシー
      %li
        メルカリ利用規約
      %li
        特定商取引に関する表記
  =link_to "https://www.mercari.com/jp/", class: "single-footer-logo" do
    =image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?3791839826", alt: "mercari", class: "single-footer-logo",size:'80px*65px'
  .footer-campany-name
    © 2019 Mercari

app/views/items/index.html.haml
= render "modules/header"
= render "modules/sell-btn"
%main
  .slider-wrapper
    .slide-item
      = image_tag 'merukari3.png'
    .slide-item
      = image_tag 'merukari.png'
    .slide-item
      = image_tag 'merukari2.png'
  .pickup
    %h2.pickup__heading ピックアップカテゴリー
    .pickup__item
      %h3.pickup__item__category
        .pickup__item__category__title  レディース 新着アイテム
        - @items_for_woman.each do |item|
          .pickup__item__box__content
            = link_to item_path(item) do
              .pickup__item__box__content__link
                .pickup__item__price
                  ="￥#{item.price}"
                = image_tag item.item_images.first.image_url,class: "top_image",alt: "商品画像"
              .pickup__item__box__content__link__body
                .pickup__item__box__content__link__body__name
                  = item.name
      .pickup__item__all
        %p.pickup__item__all__link 全ての商品を見る
    .pickup__item
      %h3.pickup__item__category
        .pickup__item__category__title  メンズ 新着アイテム
        - @items_for_man.each do |item|
          .pickup__item__box__content
            = link_to item_path(item) do
              .pickup__item__box__content__link
                = image_tag item.item_images.first.image_url,class: "top_image",alt: "商品画像", size: "213x220"
                .pickup__item__price
                  ￥
                  = item.price
              .pickup__item__box__content__link__body
                .pickup__item__box__content__link__body__name
                  = item.name
      .pickup__item__all
        %p.pickup__item__all__link 全ての商品を見る
    .pickup__item
      %h3.pickup__item__category
        .pickup__item__category__title  インテリア 新着アイテム
        - @items_for_sports.each do |item|
          .pickup__item__box__content
            = link_to item_path(item) do
              .pickup__item__box__content__link
                = image_tag item.item_images.first.image_url,class: "top_image",alt: "商品画像", size: "213x220"
                .pickup__item__price
                  ￥
                  = item.price
              .pickup__item__box__content__link__body
                .pickup__item__box__content__link__body__name
                  = item.name
      .pickup__item__all
        %p.pickup__item__all__link 全ての商品を見る
    .pickup__item
      %h3.pickup__item__category
        .pickup__item__category__title  SPORTS 新着アイテム
        - @items_for_interior.each do |item|
          .pickup__item__box__content
            = link_to item_path(item) do
              .pickup__item__box__content__link
                = image_tag item.item_images.first.image_url,class: "top_image",alt: "商品画像", size: "213x220"
                .pickup__item__price
                  ￥
                  = item.price
              .pickup__item__box__content__link__body
                .pickup__item__box__content__link__body__name
                  = item.name
      .pickup__item__all
        %p.pickup__item__all__link 全ての商品を見る
= render "modules/footer"

app/views/items/logout.html.haml
%nav.bread-crumbs
  .bread-crumbs-box
    = link_to 'https://www.mercari.com/jp/', class: "contents" do
      メルカリ
      = fa_icon 'angle-double-right'
    = link_to 'https://www.mercari.com/jp/mypage/', class: "contents" do
      マイページ
      = fa_icon 'angle-double-right'
    %span{itemprop: "title"} ログアウト

.logout_main-content
  .logout_left-content
    = render 'modules/mypage-sidebar'

  .logout_right-content
    .logout_right-container
      %form{action: "https://www.mercari.com/jp/logout/", method: "POST", novalidate: "novalidate"}
        .logout_right-form
          %button{type: "submit"} ログアウト
          %input{name: "__csrf_value", type: "hidden", value: ""}/

app/views/items/show.html.haml
= render 'modules/header'

%section.item-box-container
  %h1.item-name
    = @item.name
  .item-main-content
    .item-main-content-photo
      .owl-item-inner
        = image_tag @item.item_images.first.image_url,alt: "商品画像"
        .owl-item-inner-sub-box
        - @images.each do |image|
          .owl-item-inner-sub
            = image_tag image.image_url
    .visible-sp
    .item-btn-float-area
      %a.item-btn-client
    .item-detail-table
      .tr
        .th 出品者
        .td
          = @item.user.nickname
          %div
            .item-user
      .tr
        .th-sub-children カテゴリー
        .td-sub-children
          = @item.category.root.name
          %br/
          = fa_icon 'angle-double-right'
          = @item.category.parent.name
          %br/
          = fa_icon 'angle-double-right'
          = @item.category.parent.name

      .tr
        .th ブランド
        .td
          = @item.brand
      .tr
        .th 商品のサイズ
        .td
      .tr
        .th 商品の状態
        .td
          =@item.item_state.item_state
      .tr
        .th 配送料の負担
        .td
          = @item.delivery_fee.delivery_fee
      .tr
        .th 配送の方法
        .td クロネコヤマト
      .tr
        .th 配送元地域
        .td 東京
      .tr
        .th 発送日の目安
        .td
          = @item.delivery_day.delivery_day
  .item-price-box.text-center
    %span.item-price.bold
      ￥
      = @item.price
    %span.item-tax 円(税込)
    %span.item-shipping-fee 送料込み
  - if @item.user_id == current_user.id
    .text-center
      .item-buy-btn
        = link_to '商品を削除する', item_path(@item),method: :delete
  - else
    .text-center
      .item-buy-btn
        = link_to '購入画面に進む', purchase_cards_path( item_id: @item )
  .item-description.f14
    %p.item-description-inner
      = @item.description
  .item-button-container
    .item-button-container-left
      %button.item-button.item-button-like{"data-ga": "element", "data-ga-category": "LIKE", "data-ga-label": "like!", "data-id": "m11168273272", "data-toggle": "like", name: "like!", type: "button"}
        %span いいね!
        %span.fade-in-down{"data-num": "like"} 21
      %a.item-button.item-button-report
        %span 不適切な商品の報告
    .item-button-container-right
      %span あんしん・あんぜんへの取り組み
  .message-content
    .comments-container
    - if current_user
      = form_tag("/jp/items/#{@item.id}/item_comments", method: :post) do
        %textarea{:cols => "30", :name => "comment", :placeholder => "相手のことを考え丁寧なコメントを心がけましょう。\n不快な言葉遣いなどは利用制限や退会処分となることがあります。", :rows => "2"}
        %input{:type => "submit", :value => "コメントする"}/
    .comments
      %h4 ＜コメント一覧＞
      - if @comments
        - @comments.each do |comment|
          %p
            %strong
              = link_to comment.user.nickname
            = comment.comment
  .item-link
    .item-link-prev
      -if @prev_item.present?
        = link_to item_path(@prev_item), class: 'prev-next-left' do
          =fa_icon 'chevron-left'
          %span
            = @prev_item.name
    .item-link-next
      -if @next_item.present?
        = link_to item_path(@next_item), class: 'prev-next--right' do
          %span
            = @next_item.name
            = fa_icon 'chevron-right'
  .item-social-media-box
  %ul.social-media-box
    = fa_icon 'facebook-square', class: "contents-icon"
    = fa_icon 'twitter-square', class: "contents-icon"
    = fa_icon 'pinterest', class: "contents-icon"
  %h2.items-box-head
    = @item.user.nickname
    さんの出品
  .items-box-content1
  .pickup__item__category__title
  - @item_user.each do |user|
    .pickup__item__box__content
      = link_to item_path(user) do
        .pickup__item__box__content__link
          = image_tag user.item_images.first.image_url,class: "top_image",alt: "商品画像", size: "213x220"
          .pickup__item__box__content__link__body
            .pickup__item__box__content__link__body__name
              = user.name
          .pickup__item__detail__price
            ￥
            = user.price
  .items-box-content1
  %h2.items-box-head_sub
    おすすめアイテム
  .pickup__item__category__title
  - @products.each do |product|
    .pickup__item__box__content
      = link_to item_path(product) do
        .pickup__item__box__content__link
          = image_tag product.item_images.first.image_url,class: "top_image",alt: "商品画像", size: "213x220"
          .pickup__item__box__content__link__body
            .pickup__item__box__content__link__body__name
              = product.name
          .pickup__item__detail__price
            ￥
            = product.price
= render "modules/footer"

app/views/items/test6.html.haml
.sign-up__header
  =link_to root_path do
    =image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?863353983", alt: "mercari", class: "sign-up__header--image"
  .step_bar
    %ul.cp_stepflow01
      %li.completed
        会員情報
        %span.bubble
      %li.completed
        電話番号認証
        %span.bubble
      %li.completed
        お届け先住所入力
        %span.bubble
      %li.completed
        支払い方法
        %span.bubble
      %li.active_step
        完了
        %span.bubble>
.sign-up__main
  .sign-up__main__header
    %h2.sign-up__main__header__main-title 会員登録完了
  .sign-up__main__body
    .sign-up__main__body__forms-container
      .sign-up__main__body__forms-container__form-box
        %h2 ありがとうございます。
        %h2 会員登録が完了しました。
      .sign-up__main__body__forms-container__form-box
        = link_to "メルカリをはじめる", root_path, class: "form__sent-btn"

  .complete-footer
    .complete-footer__inner-left-box
      .complete-footer__inner-left-box__index
        %h2 \スマホでかんたんフリマアプリ/
        %p 今すぐ無料ダウンロード！
      .complete-footer__inner-left-box__icon
        .complete-footer__inner-left-box__icon--left
          =image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?863303983",class:"banner-icon",size:'60x60'
        .complete-footer__inner-left-box__icon--right
          %ul
            =link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8", target: "_blank" do
              =image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?863303983", alt: "", class: "banner-button"
            =link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja", target: "_blank" do
              =image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?863303983", alt: "", class: "bannar-button"
    .complete-footer__inner-right-box

.sign-up__footer
  %nav
    %ul
      %li
        プライバシーポリシー
      %li
        メルカリ利用規約
      %li
        特定商取引に関する表記
  =link_to "https://www.mercari.com/jp/", class: "single-footer-logo" do
    =image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?3791839826", alt: "mercari", class: "single-footer-logo",size:'80px*65px'
  .footer-campany-name
    © 2019 Mercari

app/views/items/test7.html.haml
.sign-up__header
  =link_to root_path do
    =image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?863303983", alt: "mercari", class: "sign-up__header--image"
.sign-up__main
  .sign-up__main__header
    %h1.sign-up__main__header__main-title  新規会員登録
  .sign-up__main__body
    .sign-up__main__body__forms-container
      .sign-up__main__body__forms-container__form-box
        =link_to root_path, class: "sign-up__by--mail" do
          .sign-up__by--mail--left
            =fa_icon "envelope"
          .sign-up__by--mail--right
            メールアドレスで登録する
        =link_to  "/users/auth/facebook", class: "facebook" do
          .facebook--left
            =fa_icon "facebook-square"
          .facebook--right
            Facebookで登録する
        =link_to "/users/auth/google_oauth2", class: "google" do
          .google--left
            =fa_icon "google"
          .google--right
            Googleで登録する

.sign-up__footer
  %nav
    %ul
      %li
        プライバシーポリシー
      %li
        メルカリ利用規約
      %li
        特定商取引に関する表記
  =link_to "https://www.mercari.com/jp/", class: "single-footer-logo" do
    =image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?3791839826", alt: "mercari", class: "single-footer-logo",size:'80px*65px'
  .footer-campany-name
    © 2019 Mercari