config/routes.rb
Rails.application.routes.draw do

# 本家のメルカリのパスに合わせるためscopeを用いてルーティングを作成した

  # deviseGem配下で動くもの
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'user/registrations',
    # google,facebook連携ログイン用
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  scope :jp do
    # 商品一覧表示（トップページ）
    get '/'                => 'items#index'  ,as: "root"
    # 商品詳細ページ
    # get 'items/:id'      => 'items#show' (なんかこれがあると商品出品ページに飛べないので後で要確認)
    scope :mypage do
      get '/'              => 'users#mypage' ,as: "mypage"
      get 'profile'        => 'users#show'
      get 'identification' => 'users#identification'
      get 'logout'         => 'users#logout'
      get 'myitems'        => 'users#myitems'
      resources :cards, only: [:new] do
        collection do
          get  'show'      => 'cards#show'
          post 'pay'       => 'cards#pay'
          # 登録カード情報の削除
          post 'delete'    => 'cards#delete'
          # カード情報の登録のアクション
          get  'add'       => 'cards#add'
          # 購入内容の確認ページ
          get  'index'     => 'cards#index',as:"purchase"
          # カード決済のアクション
          post 'paypay'    => 'cards#paypay'
        end
      end
    end
    
    scope :transaction do
      scope :buy do
        get 'm[:id]/sell'  => 'items#transaction'
      end
    end
    # resources :item_images, only: [:create,:destroy,:update], defaults: { format: 'json' }
    #商品周りのルート
    resources :items, only: [:show, :new,:create, :edit, :update, :destroy] do
      #商品出品ページに関する、Ajaxで動くアクションのルートを作成
      collection do
        get 'purchase'     => 'items#purchase'
        get 'get_category_children', defaults: { format: 'json' }
        get 'get_category_grandchildren', defaults: { format: 'json' }
        get 'get_size', defaults: { format: 'json' }
      end
      resources :item_comments, only: [:create] do
      end
    end
  end
  
  # ユーザ新規会員登録ページ
  devise_scope :user do
    scope :jp do
      scope :signup do
        get  '/'                    => 'users/registrations#new'
        get  'registration'         => 'users/registrations#step1'
        get  'ms_confirmation'      => 'users/registrations#step2'
        get  'sms_confirmation/sms' => 'users/registrations#step3'
        get  'address'              => 'users/registrations#step4'
        get  'credit'               => 'users/registrations#step5'
        post 'registration/create'  => 'users/registrations#create'
        get  'check'                => 'users/registrations#check'
        get  'emailCheck'           => 'users/registrations#email_check'
      end
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  require "payjp"

  if Rails.env.production?
    Payjp.api_key = Rails.application.credentials.payjp_private_key
  else
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
  end

  def index
    @item = Item.find(params[:item_id])
    @address = Address.find(current_user.id)
    card = Card.where(user_id: current_user.id).first
    #Cardテーブルは前回記事で作成、テーブルからpayjpの顧客IDを検索
    if card.blank?
      #登録された情報がない場合にカード登録画面に移動
      redirect_to action: "new"
    else
      Payjp.api_key
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(card.customer_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def paypay
    card = current_user.card
    Payjp.api_key
    Payjp::Charge.create(
    amount: params[:item][:item_price], #支払金額を入力（itemテーブル等に紐づけても良い）
    customer: card.customer_id, #顧客ID
    currency:'jpy', #日本円
  )
  item = Item.find(card_params[:id])
  item.destroy
  redirect_to root_path #完了画面に移動
  end

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to cards_path if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
        card: params['payjp-token'],
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        card = Card.where(user_id: current_user.id)
        redirect_to cards_path
      else
        redirect_to action: "pay"
      end
    end
  end
  
  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
    redirect_to action: "add"
  end

  def add
  end


  def show #Cardのデータpayjpに送り情報を取り出します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  private
  def card_params
    params.require(:item).permit(:id)
  end
end

app/controllers/jp/mypage/card/cards_controller.rb
class Jp::Mypage::Card::CardsController < ApplicationController
  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def destroy
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/add.html.haml
= render "modules/header"
%nav.bread-crumbs
  .bread-crumbs-box
    = link_to '/jp', class: "contents" do
      メルカリ
      = fa_icon 'angle-double-right'
    = link_to '/jp/mypage', class: "contents" do
      マイページ
      = fa_icon 'angle-double-right'
    %span{itemprop: "title"} 支払い方法
.main-content
  = render "modules/mypage-sidebar"
  .l-content
    .l-container
      .l-content
        %section.l-chapter-container
          %h2.l-chapter-head 支払い方法
          .l-single-inner
            %section
              .l-single-content
                %h3.l-chapter-sub-head クレジットカード一覧
              %ul.settings-payment-list
            %section.settings-add-card
              .l-single-content
                .btn-default.btn-red.submit_button
                  %i.icon-card>
                  = link_to '/jp/mypage/cards/new', class: "contents" do
                    クレジットカードを追加する
            .settings-not-regist
              %a{:href => "/jp/help_center/category/6/", :target => "_blank"}
                %span 支払い方法について
                %i.icon-arrow-right


= render "modules/sell-btn"

= render "modules/footer"

app/views/cards/edit.html.haml
= render "modules/header"
%nav.bread-crumbs
  .bread-crumbs-box
    = link_to '/jp', class: "contents" do
      メルカリ
      = fa_icon 'angle-double-right'
    = link_to '/jp/mypage', class: "contents" do
      マイページ
      = fa_icon 'angle-double-right'
    %span{itemprop: "title"} 支払い方法
.main-content
  = render "modules/mypage-sidebar"
  .l-content
    .l-container
      .l-content
        %section.l-chapter-container
          %h2.l-chapter-head 支払い方法
          .l-single-inner
            %section
              .l-single-content
                %h3.l-chapter-sub-head クレジットカード一覧
              %ul.settings-payment-list
            %section.settings-add-card
              .l-single-content
                %a.btn-default.btn-red.submit_button{:href => "https://www.mercari.com/jp/mypage/card/create/"}
                  %i.icon-card>
                  クレジットカードを追加する
            .settings-not-regist
              %a{:href => "/jp/help_center/category/6/", :target => "_blank"}
                %span 支払い方法について
                %i.icon-arrow-right


= render "modules/sell-btn"

= render "modules/footer"

app/views/cards/index.html.haml
.single-container
  .single-header
    =link_to root_path do
      =image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?863353983", alt: "mercari", class: "sign-up__header--image"


.single-main
  %section.l-single-container.buy-item-container
    %h2.l-single-head 購入内容の確認
    %section.buy-content.buy-item
      .buy-content-inner
        .buy-pro
          .buy-item-image
            = image_tag @item.item_images.first.image_url,class: "buy-item-image",alt: "商品画像", size: "120x130"
          %p.buy-item-name
            = @item.name
        %form.buy-form
          %p.buy-price-ja.bold
            ¥
            = @item.price
            %span.item-shipping-fee.f14.bold 送料込み
          %ul.buy-accordion
            %li.accordion-parent
          %ul.buy-price-table
            %li.buy-price-row.buy-you-pay.bold
              .buy-price 支払い金額
              .buy-price-cell
                ￥
                = @item.price
          %p.has-error-text 配送先と支払い方法の確認を完了してください。

    %section.buy-content.buy-user-info
      .buy-content-inner
        %h3 配送先
        .buy-user-info-text
          〒
          = @address.post_number
          %br/
          = @address.prefecture.name
          %br/
          = @address.city
          %br/
          = @address.address
          %br/
          = @address.building_name
          %br/
          =  current_user.first_name
          =  current_user.last_name
        %p.buy-user-info-text
        .buy-user-info-fix
          %span 変更する
          %i.icon-arrow-right
    %section.buy-content.buy-user-info
      .buy-content-inner
        %h3 支払い方法
        - if @default_card_information.blank?
          %br/
        - else
        .buy-user-info-text
          = "**** **** **** " + @default_card_information.last4
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year
        %br
        .buy-user-info-fix
          %span 変更する
          %i.icon-arrow-right

          .buy-content-purchase
          = form_for @item,url: paypay_cards_path,method: :post do |f|
            = f.hidden_field :item_price, value: @item.price.to_i
            = f.hidden_field :id, value: @item.id
            = f.submit "購入する", class:"buy-content-purchase-btn"
  .single-footer-purchase
    %nav
      %ul.clearfix
        %li
          %a プライバシーポリシー
        %li
          %a メルカリ利用規約
        %li
          %a 特定商取引に関する表記
    %a.single-footer-logo
      %img{:alt => "mercari", :height => "65", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?273499512", :width => "80"}/
    %p
      %small © 2019 Mercari

app/views/cards/new.html.haml
= render "modules/header"
%nav.bread-crumbs
  .bread-crumbs-box
    = link_to '/jp', class: "contents" do
      メルカリ
      = fa_icon 'angle-double-right'
    = link_to '/jp/mypage', class: "contents" do
      マイページ
      = fa_icon 'angle-double-right'
    = link_to '/jp/mypage/card/', class: "contents" do
      支払い方法
      = fa_icon 'angle-double-right'
    %span クレジットカード情報入力
.main-content
  = render "modules/mypage-sidebar"
  %section.l-chapter-container
    .l-chapter-head クレジットカード情報入力
    .l-single-inner.registration-form
      .l-single-content
        .form-group
        = form_tag(pay_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
          %label カード番号
          %span.form-require 必須
          %input.input-default{"data-input-type": "card", maxlength: "16", placeholder: "半角数字のみ", type: "text", number: "", id: "card_number"}/
          %ul.has-error-text
          %ul.signup-card-list
            = image_tag ('https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?3951034907')
            = image_tag ('https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?3951034907')
            = image_tag ('https://www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?3951034907')
            = image_tag ('https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?3951034907')
            = image_tag ('https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?3951034907')
            = image_tag ('https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?3951034907')
            = image_tag ('https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?3951034907')
          .form-group.signup-form-expire
            %label 有効期限
            %span.form-require 必須
            %br
          .select-wrap.half-main
            .select-wrap.half-1
              %select#exp_month{name: "exp_month", type: "text", class: "select-default"}
                %option{value: "01"} 01
                %option{value: "02"} 02
                %option{value: "03"} 03
                %option{value: "04"} 04
                %option{value: "05"} 05
                %option{value: "06"} 06
                %option{value: "07"} 07
                %option{value: "08"} 08
                %option{value: "09"} 09
                %option{value: "10"} 10
                %option{value: "11"} 11
                %option{value: "12"} 12
              %i.icon-arrow-bottom
              %span 月
            .select-wrap.half-2
              %select#exp_year{name: "exp_year", type: "text", class: "select-default"}
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
              %i.icon-arrow-bottom
              %span 年
            %ul.has-error-text
            %ul.has-error-text
          .form-group
            %label セキュリティコード
            %span.form-require 必須
            %input.input-default{placeholder: "カード背面4桁もしくは3桁の番号", id: "cvc", cvc: ""}/
            %ul.has-error-text
            .signup-seqcode
              .signup-seqcode-text
                %span.form-question
                カード裏面の番号とは？
              .signup-seqcode-info
                %br/
          #card_token
          %button.btn-default{id: "token_submit"} 追加する



= render "modules/sell-btn"
= render "modules/footer"

app/views/cards/show.html.haml
= render "modules/header"
%nav.bread-crumbs
  .bread-crumbs-box
    = link_to '/jp', class: "contents" do
      メルカリ
      = fa_icon 'angle-double-right'
    = link_to '/jp/mypage', class: "contents" do
      マイページ
      = fa_icon 'angle-double-right'
    %span{itemprop: "title"} 支払い方法
.main-content
  = render "modules/mypage-sidebar"
  .l-content
    .l-container
      .l-content
        %section.l-chapter-container
          %h2.l-chapter-head 支払い方法
          .l-single-inner
            %section
              .l-single-content
                .l-chapter-sub-head クレジットカード一覧
              %ul.settings-payment-list
                %li
                  .l-single-content
                    %figure
                      = image_tag ('https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?3951034907')
                      %br
                      .settings-payment-num
                      = "**** **** **** " + @default_card_information.last4
                      %br
                      .settings-payment-num
                      - exp_month = @default_card_information.exp_month.to_s
                      - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                      = exp_month + " / " + exp_year
                      = form_tag(delete_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
                        %input{ type: "hidden", name: "card_id", value: "", class: "settings-payment-remove" }
                        %button 削除する
            .settings-not-regist
              %span 支払い方法について
              %i.icon-arrow-right




= render "modules/sell-btn"


= render "modules/footer"